// <auto-generated />
using System;
using Infrastructure.Configs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ContextBase))]
    [Migration("20211008135345_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entites.Entites.Atendimento", b =>
                {
                    b.Property<int>("IdAtendimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DAtendimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.Property<int>("OrdemId")
                        .HasColumnType("int");

                    b.Property<int>("Protocolo_Atendimento")
                        .HasColumnType("int");

                    b.Property<int>("StatusAtendimento")
                        .HasColumnType("int");

                    b.HasKey("IdAtendimento");

                    b.HasIndex("OperadorId");

                    b.HasIndex("OrdemId");

                    b.ToTable("Atendimento");
                });

            modelBuilder.Entity("Entites.Entites.Operador", b =>
                {
                    b.Property<int>("IdOperador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Atendimento")
                        .HasColumnType("int");

                    b.Property<int>("Matricula_Operador")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Operador")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOperador");

                    b.ToTable("Operador");
                });

            modelBuilder.Entity("Entites.Entites.Ordem", b =>
                {
                    b.Property<int>("IdOrdem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Atendimemto")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOrdemFinalizada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOrdemGerada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo_Solicitacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdemStatus")
                        .HasColumnType("int");

                    b.Property<string>("Solicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo_Ordem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOrdem");

                    b.ToTable("Ordem");
                });

            modelBuilder.Entity("Entites.Entites.Telefone", b =>
                {
                    b.Property<int>("IdTelefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DDD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdemId")
                        .HasColumnType("int");

                    b.HasKey("IdTelefone");

                    b.HasIndex("OrdemId");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("Entites.Entites.Atendimento", b =>
                {
                    b.HasOne("Entites.Entites.Operador", "Operador")
                        .WithMany("atendimentos")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entites.Entites.Ordem", "Ordem")
                        .WithMany()
                        .HasForeignKey("OrdemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operador");

                    b.Navigation("Ordem");
                });

            modelBuilder.Entity("Entites.Entites.Telefone", b =>
                {
                    b.HasOne("Entites.Entites.Ordem", "Ordem")
                        .WithMany()
                        .HasForeignKey("OrdemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordem");
                });

            modelBuilder.Entity("Entites.Entites.Operador", b =>
                {
                    b.Navigation("atendimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
